# cronjob.yaml
apiVersion: batch/v1beta1
kind: CronJoblhjk
metadata:
  name: netimpact
spec:
  schedule: "0 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: netimpact
            image: eu.gcr.io/netimpact/netimpact
          restartPolicy: OnFailure